INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Stephen, Curry, Point Guard, 27.3, 47.2, 43.7, 91.6, 5.3, 5.2, 1.3, 0.4, 95)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Damian, Lillard, Point Guard, 25.8, 44.4, 36.9, 91.2, 4.6, 6.9, 1.1, 0.4, 92)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Russell, Westbrook, Point Guard, 22.9, 42.8, 29.0, 65.6, 11.1, 10.7, 1.9, 0.5, 90)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Mike, Conley, Point Guard, 21.1, 43.8, 36.4, 84.5, 3.4, 6.4, 1.3, 0.3, 87)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Jamal, Murray, Point Guard, 18.2, 43.7, 36.7, 84.8, 4.2, 4.8, 0.9, 0.4, 87)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (DaAaron, Fox, Point Guard, 17.3, 45.8, 37.1, 72.7, 3.8, 7.3, 1.6, 0.6, 83)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Chris, Paul, Point Guard, 15.6, 41.9, 35.8, 86.2, 4.6, 8.2, 2.0, 0.3, 87)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Dennis, Schroder, Point Guard, 15.5, 41.4, 34.1, 81.9, 3.6, 4.1, 0.8, 0.2, 77)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Ricky, Rubio, Point Guard, 12.7, 40.4, 31.1, 85.5, 3.6, 6.1, 1.3, 0.1, 77)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Monte, Morris, Point Guard, 10.4, 49.3, 41.4, 80.2, 2.4, 3.6, 0.9, 0.0, 0.6, 78)



INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (James, Harden, Shooting Guard, 36.1, 44.2, 36.8, 87.9,7.5, 2.0, 0.7, 96)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Paul, George, Shooting Guard, 28.0, 43.8, 38.6, 83.9, 8.2, 4.1, 2.2, 0.4, 93)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Devin, Booker, Shooting Guard, 26.6, 46.7, 32.6, 86.6, 6.8, 0.9, 0.2, 88)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Donovan, Mitchell, Shooting Guard, 23.8, 43.2, 36.2, 80.6, 4.1, 4.2, 1.4, 0.4, 87)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Klay, Thompson, Shooting Guard, 21.5, 46.7, 40.2, 81.6, 3.8, 2.4, 1.1, 0.6, 88)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Luka, Doncic, Shooting Guard, 21.2, 42.7, 32.7, 71.3, 7.8, 6.0, 1.1, 0.3, 87)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Jrue, Holiday, Shooting Guard, 21.2, 47.2, 32.5, 76.8, 5.0, 7.7, 1.6, 0.8, 86)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (CJ, McCollum, Shooting Guard, 21.0, 45.9, 37.5, 82.8, 4.0, 3.0, 0.8, 0.4, 85)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Buddy, Hield, Shooting guard, 20.7, 45.8, 42.7, 88.6, 5.0, 2.5, 0.7, 0.4, 83)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Lou, Williams, Shooting guard, 20.0, 42.5, 36.1, 87.6, 3.0, 5.4, 0.8, 0.1, 85)



INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Kevin, Durant, Small Forward, 26.0, 52.1, 35.3, 88.5, 6.4, 5.9, 0.7, 1.1, 95)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (DeMar, DeRozan, Small Forward, 21.2, 48.1, 15.6, 83.0, 6.0, 6.2, 1.1, 0.5, 89)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Andrew, Wiggins, Small Forward, 18.1, 41.2, 33.9, 69.9, 4.8, 2.5, 1.0, 0.7, 80)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Harrison, Barnes, Small Forward, 16.4, 42.0, 39.5, 82.4, 4.7, 1.5, 0.6, 0.2, 79)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Rudy, Gay, Small Forward, 13.7, 50.4, 40.2, 81.6, 6.8, 2.6, 0.8, 0.5, 81)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Jae, Crowder, Small Forward, 11.9, 39.9, 33.1, 72.1, 4.8, 1.7, 0.8, 0.4, 76)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Mikal, Bridges, Small Forward, 8.3, 43.0, 33.5, 80.5, 3.2, 2.1, 1.6, 0.5, 75)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Darius, Miller, Small Forward, 8.2, 39.0, 36.5, 78.9, 1.9, 2.1, 0.6, 0.3, 71)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Davis, Bertans, Small Forward, 8.0, 45.0, 42.9, 88.3, 3.5, 1.3, 0.5, 0.4, 76)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Josh, Hart, Small Forward, 7.8, 40.7, 33.6, 68.8, 3.7, 1.4, 1.0, 0.6, 74)



INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Julius, Randle, Power Forward, 21.4, 52.4, 34.4, 73.1, 8.7, 3.1, 0.7, 0.6, 85)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (LaMarcus, Aldridge, Power Forward, 21.3, 51.9, 23.8, 84.7, 9.2, 2.4, 0.5, 1.3, 88)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Danilo, Gallinari, Power Forward, 19.8, 46.3, 43.3, 90.4, 6.1, 2.6, 0.7, 0.3, 85)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Kyle, Kuzma, Power Forward, 18.7, 45.6, 30.3, 75.2, 5.5, 2.5, 0.6, 0.4, 83)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Montrezl, Harrell, Power Forward, 16.6, 61.5, 17.6, 64.3, 6.5, 2.0, 0.9, 1.3, 84)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Marvin, Bagley III, Power Forward, 14.9, 50.4, 31.3, 69.1, 7.6, 1.0, 0.5, 1.0, 81)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Jaren, Jackson Jr, Power Forward, 13.8, 50.6, 35.9, 76.7, 4.7, 1.1, 0.9, 1.4, 80)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Jerami, Grant, Power Forward, 13.6, 49.7, 39.2, 71.0, 5.2, 1.0, 0.8, 1.3, 77)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Paul, Millsap, Power Forward, 12.6, 48.4, 36.5, 72.7, 7.2, 2.0, 1.2, 0.8, 83)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Dario, Saric, Power Forward, 10.5, 45.4, 38.3, 87.5, 5.5, 1.5, 0.6, 0.1, 77)



INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Karl-Anthony, Towns, Center, 24.4, 51.8, 40.0, 83.6, 12.4, 3.4, 0.9, 1.6, 91)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Nikola, Jokic, Center, 20.1, 51.1, 30.7, 82.1, 10.8, 7.3, 1.4, 0.7, 92)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Clint, Capela, Center, 16.6, 64.8, 0.0, 63.6, 12.7, 1.4, 0.7, 1.5, 87)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Deandre, Ayton, Center, 16.3, 58.5, 0.0, 74.6, 10.3, 1.8, 0.9, 0.9, 84)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Rudy, Gobert, Center, 15.9, 66.9, 0.0, 63.6, 12.9, 2.0, 0.8, 2.3, 89)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Jusuf, Nurkic, Center, 15.6, 50.8, 10.3, 77.3, 10.4, 3.2, 1.0, 1.4, 85)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Steven, Adams, Center, 13.9, 59.5, 0.0, 50.0, 9.5, 1.6, 1.5, 1.0, 84)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (JaVale, McGee, Center, 12.0, 62.4, 8.3, 63.2, 7.5, 0.7, 0.6, 2.0, 80)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Willie, Cauley-Stein, Center, 11.9, 55.6, 50.0, 55.1, 8.4, 2.4, 1.2, 0.6, 80)
INSERT INTO players (firstname, lastname, positionname, pointspergame, fieldgoal, threepoint, freethrowpercent, rebounds, assists, steals, blocks, overallstats) VALUES (Derrick, Favors, Center, Center, 11.8, 58.6, 21.8, 67.5, 7.4, 1.2, 0.7, 1.4, 81)